### ISSUE TITLE
[doc] Issue in "Post-installation tasks"

### ISSUE THREAD

**Issue by Wabri** [SUSE/suse-best-practices#396]
In the *Post-installation tasks* section there is the `ingress.yaml` cannot work as is, the one I've used to get the SAP installation done is the one below:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/secure-backends: "true"
  name: vsystem
spec:
  defaultBackend:
  	service:
    	  name: vsystem
          port:
            number: 8797
  ingressClassName: nginx
  tls:
  - hosts:
    - "<hostname FQDN must match SSL certificate>"
    secretName: vsystem-tls-certs
```

https://documentation.suse.com/sbp/sap/html/SAPDI-RKE-Harvester/index.html#id-post-installation-tasks
